theme: jekyll-theme-minimal
title: Shantiram Mahata's homepage
description: I am a postdoc at Umea University ![My Photo](https://avatars.githubusercontent.com/u/111852870?v=4)
markdown: kramdown
mathjax: true
